ALTER TABLE "clubs" ADD COLUMN IF NOT EXISTS "introduction" TEXT;
ALTER TABLE "clubs" ADD COLUMN IF NOT EXISTS "policy" TEXT;
ALTER TABLE "clubs" ADD COLUMN IF NOT EXISTS "banner_image" TEXT;
ALTER TABLE "clubs" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "clubs" ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMP(3);
