services:
  db:
    image: postgres:18
    container_name: mycologs-postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mycologs

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/18/main

volumes:
  pgdata: