import anthropic as _anthropic
from mycologs_ai_service.core.anthropic_client import client
from mycologs_ai_service.api.identification.schemas import IdentificationRequest, IdentificationResult

MODEL = "claude-opus-4-7"
AGENT_VERSION = f"{MODEL}/prompt-v2.1"

SYSTEM_PROMPT = """\
あなたは日本の菌類を専門とするマイコロジスト（菌類学者）です。
与えられたキノコの写真をもとに同定を行い、report_identification ツールを使って結果を返してください。

同定にあたっての指針:
- 撮影地は日本国内と仮定し、日本に自生または定着している種のみを考慮する
- key_features には目視で確認できる特徴を 2〜4 点、初心者にも分かる言葉で挙げる
- similar_species には外見が紛らわしい種を 0〜2 種挙げ、見分け方を具体的に説明する
- missing_info には同定の確度を上げるために必要だが画像から判断できない情報を挙げる（例: 胞子紋の色、柄の基部の形状、匂いなど）
- 画像にキノコが写っていない場合は scientific_name を空文字にし、disclaimer にその旨を記載する
- disclaimer には食用判断を AI に委ねないよう促す安全上の注意を必ず含める
- すべてのフィールドは日本語で記述する"""

def _build_input_schema() -> dict:
    schema = IdentificationResult.model_json_schema()
    # agent_version is stamped by the service, not generated by the model
    schema["properties"].pop("agent_version", None)
    return schema

_TOOL: _anthropic.types.ToolParam = {
    "name": "report_identification",
    "description": "キノコの同定結果を構造化データとして報告する",
    "input_schema": _build_input_schema(),
}


def evaluate(payload: IdentificationRequest) -> IdentificationResult:
    """
    Blocking call — intended to be run via asyncio.to_thread() in async contexts.
    """
    image_blocks: list[_anthropic.ImageBlockParam] = [
        {
            "type": "image",
            "source": {
                "type": "base64",
                "media_type": img.media_type,
                "data": img.data,
            },
        }
        for img in payload.images
    ]

    has_coords = payload.latitude is not None and payload.longitude is not None
    location_line = (
        f"GPS: 緯度 {payload.latitude}、経度 {payload.longitude}"
        if has_coords
        else "GPS情報なし。日本国内のどこかと仮定してください。"
    )
    hint_line = f"\n投稿者からのヒント: {payload.hint}" if payload.hint else ""
    multi_line = "\n複数の画像を総合的に見て同定してください。" if len(payload.images) > 1 else ""
    user_text = f"{location_line}{hint_line}{multi_line}"

    text_block: _anthropic.TextBlockParam = {"type": "text", "text": user_text}

    message = client.messages.create(
        model=MODEL,
        max_tokens=1024,
        system=SYSTEM_PROMPT,
        tools=[_TOOL],
        tool_choice={"type": "tool", "name": "report_identification"},
        messages=[{"role": "user", "content": [*image_blocks, text_block]}],
    )

    tool_use = next((b for b in message.content if b.type == "tool_use"), None)
    if tool_use is None:
        raise ValueError(f"No tool_use block in response. stop_reason={message.stop_reason}, content={message.content}")
    return IdentificationResult(**tool_use.input, agent_version=AGENT_VERSION)
